import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import dalleService from '@/services/dalleService';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export default function DalleTest() {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [logs, setLogs] = useState<string[]>([]);
  const [customPrompt, setCustomPrompt] = useState<string>(
    'A delicious plate of pasta with tomato sauce'
  );

  const addLog = (message: string) => {
    setLogs(prev => [...prev, `${new Date().toLocaleTimeString()}: ${message}`]);
  };

  const testDalleService = async () => {
    setIsLoading(true);
    setError(null);
    addLog('Starting DALL-E service test...');

    try {
      // Test with the debug mode first
      addLog('Testing with debug mode...');
      const url = await dalleService.testDalleService();
      addLog(`Debug test successful! Image URL: ${url}`);
      setImageUrl(url);

      // If debug mode worked, try with a custom prompt
      if (customPrompt) {
        addLog(`Testing with custom prompt: "${customPrompt}"`);
        try {
          const customUrl = await dalleService.generateImage(customPrompt);
          addLog(`Custom prompt test successful! Image URL: ${customUrl}`);
          setImageUrl(customUrl);
        } catch (customErr) {
          addLog(
            `Custom prompt test failed: ${customErr instanceof Error ? customErr.message : String(customErr)}`
          );
          // Don't set error here since the debug mode worked
        }
      }
    } catch (err) {
      console.error('DALL-E test error:', err);
      const errorMessage = err instanceof Error ? err.message : String(err);
      setError(errorMessage);
      addLog(`Test failed with error: ${errorMessage}`);
    } finally {
      setIsLoading(false);
      addLog('Test completed.');
    }
  };

  return (
    <Card className="w-full max-w-2xl mx-auto mt-8">
      <CardHeader>
        <CardTitle>DALL-E Service Test</CardTitle>
        <CardDescription>Test the DALL-E image generation service</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="prompt">Custom Prompt</Label>
              <Input
                id="prompt"
                value={customPrompt}
                onChange={e => setCustomPrompt(e.target.value)}
                placeholder="Enter a prompt for DALL-E"
              />
            </div>

            <div className="h-64 overflow-y-auto p-3 bg-muted rounded-md font-mono text-xs">
              {logs.length === 0 ? (
                <p className="text-muted-foreground">No logs yet. Run the test to see results.</p>
              ) : (
                logs.map((log, index) => (
                  <div key={index} className="mb-1">
                    {log}
                  </div>
                ))
              )}
            </div>

            {error && (
              <div className="p-4 text-white bg-red-500 rounded-md">
                <p className="font-medium">Error:</p>
                <p>{error}</p>
              </div>
            )}
          </div>

          <div className="flex flex-col items-center justify-center">
            {imageUrl ? (
              <div className="relative w-full h-64 overflow-hidden rounded-md">
                <img
                  src={imageUrl}
                  alt="Generated by DALL-E"
                  className="object-cover w-full h-full"
                />
              </div>
            ) : (
              <div className="w-full h-64 flex items-center justify-center bg-muted rounded-md">
                <p className="text-muted-foreground">No image generated yet</p>
              </div>
            )}
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button onClick={testDalleService} disabled={isLoading} className="w-full">
          {isLoading ? 'Testing...' : 'Test DALL-E Service'}
        </Button>
      </CardFooter>
    </Card>
  );
}
